# op

image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_USER:  $DOCKER_USER
  DOCKER_PASSWORD:  $DOCKER_PASSWORD

stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  
build-backend: # This job runs in the build stage to build the backend, which runs first.
  stage: build
  script:
    - echo "Compiling the backend..."
    - echo "Success!!"

build-frontend: # This job runs in the build stage to build the frontend, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

test-job-frontend: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running frontend tests..."
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Success!!"

test-job-backend: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running backend tests..."
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Success!!"

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
